In [2]:
import numpy as np

In [35]:
print(np.__version__)

1.16.4


In [36]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
b = np.arange(24).reshape(2,3,4)  
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [11]:
a.dtype

dtype('int32')

In [12]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [13]:
x = np.array([(1.5,2,3), (4,5,6)])
x

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [14]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
np.empty( (2,3) ) 

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [20]:
np.arange( 10, 60, 5 )

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [21]:
np.arange( 0, 2, 0.3 ) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [22]:
np.linspace( 0, 2, 9 )  

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
from numpy import pi

In [28]:
x = np.linspace( 0, 2*pi, 100 )
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [27]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [32]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [33]:
c = a-b
c

array([20, 29, 38, 47])

In [34]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [38]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [39]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [40]:
bool_arr = np.array([1, 0.5, 0, None, 'a', '', True, False], dtype=bool)
print(bool_arr)

[ True  True False False  True False  True False]


In [49]:
q = np.repeat(1, 10).reshape(2,-1)
q

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
w = np.arange(10).reshape(2,-1)
w

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
np.vstack([q, w])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
np.concatenate([q, w], axis=0)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
np.hstack([q, w])

array([[1, 1, 1, 1, 1, 0, 1, 2, 3, 4],
       [1, 1, 1, 1, 1, 5, 6, 7, 8, 9]])

In [56]:
np.c_[q, w]

array([[1, 1, 1, 1, 1, 0, 1, 2, 3, 4],
       [1, 1, 1, 1, 1, 5, 6, 7, 8, 9]])

In [59]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [60]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [61]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [62]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [3]:
ac = np.array([1.1,2.5,3.4,4.5])
np.ceil(ac)

array([2., 3., 4., 5.])

In [4]:
x = np.ones((100, 100))
np.any(x != 1)

False

In [5]:
np.random.gamma(4)

5.976810780196165

In [6]:
np.random.uniform(size =(3,3))

array([[0.3926098 , 0.01257384, 0.87462861],
       [0.76561516, 0.84101339, 0.02337926],
       [0.2005857 , 0.16665439, 0.36875395]])

In [7]:
np.random.normal(size = (3,3))

array([[-5.85222030e-01,  1.30949896e+00,  7.47321491e-01],
       [-1.59431172e+00, -1.77989823e+00,  7.81843987e-01],
       [ 1.28764984e-02,  1.64861786e+00, -2.63410093e-04]])

In [9]:
np.any([True, True, True, False])

True

In [10]:
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [11]:
c = np.array(['A1B C', '1BCA', 'BCA1']) 
c

array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')

In [12]:
np.prod([12,5])

60

In [13]:
np.cos(np.array([0, np.pi/2, np.pi])) 

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [14]:
np.gcd(20,4)

4

In [15]:
np.lcm(12, 20)

60

In [16]:
np.sin(np.pi/2.)

1.0

In [17]:
np.round(16.055, 2), round(16.055, 2)

(16.06, 16.05)

In [18]:
arr = np.random.randint(1,10,2)
arr

array([5, 7])

In [20]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
x = np.eye(2) + 1j * np.eye(2)
np.conjugate(x)

array([[1.-1.j, 0.-0.j],
       [0.-0.j, 1.-1.j]])